name: fetch
on:
  schedule:
    - cron:  '0 3,5,20,22 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl 'https://antal-jobb.vercel.app/api/scrape'
